### ISSUE TITLE
auth.sh: line 14: /gcds/upgrade-config: No such file or directory

### ISSUE THREAD

**Issue by xueshanf** [tiredofit/docker-gcds#5]
Tried to use docker-compose and run auth.sh in side of container. Getting the follow errors:

```[tiredofit/gcds:5.1.8 21:09:38 /gcds] $ ./auth.sh 
2022-11-25.21:09:40 [NOTICE] ** [container] 
***               GOOGLE CLOUD DIR SYNC OAUTH STEP
***
***         This script will connect to Google's Servers and provide you with a link to visit using your local web browser. 
***
***
Press any key to continue...
./auth.sh: line 14: /gcds/upgrade-config: No such file or directory
./auth.sh: line 17: /gcds/upgrade-config: No such file or directory
2022-11-25.21:09:41 [NOTICE] ** [container] *** Process Complete, you may now exit the containers shell and it should function normally..
```
I then made a symplink `upgrade-config -> /usr/local/GoogleCloudDirSync/upgrade-config`,  with a config.xml with encrypted smtp and ldap values. The process complains like this:

```[2022-11-25 20:49:12,636+0000] [main] [WARN] [usersyncapp.cli.UpgradeConfig] Upgrading configuration file "/gcds/gcds_conf.xml" to most recent version (will save a backup).
[2022-11-25 20:49:14,222+0000] [main] [FATAL] [usersyncapp.cli.UpgradeConfig] Unable to load configuration from specified file "/gcds/gcds_conf.xml" - smtpAuthPasswordEncrypted contains an invalid encrypted value 
com.google.usersyncapp.AppConfig$InvalidConfigException: smtpAuthPasswordEncrypted contains an invalid encrypted value 
        at com.google.usersyncapp.LoaderV01.loadNotification(LoaderV01.java:560) ~[DirSync.jar:?]
```

What is supposed to be in gcds_conf.xml file for the ldap and smtp password? 

Thanks!

**Comment by tiredofit** [comment]
Ah, it looks like Google has changed the install location or is not referencing the gcds.vars override I have in place.

I'll get that fixed. You'll probably want to create your config on a GUI system and then use this headless mode for the container/server operations.

**Comment by xueshanf** [comment]
Thank you! My configuration xml comes from 4.7.12 live system and I have no easy ways to a vm running gui. Would it be possible to add an 5.0.12 config.xml template in the example directory? I will test!

**Comment by xueshanf** [comment]
BTW, on one of our gcds containers, I no longer can regenerate oauth token with update-config. Get 400 errors. In upgrade notes, google says cli option will depreciate in 2022, but I am not sure if it was deprecated already. Not in release note, and still available with the cli. That’s why I looked your container to see if I can still use cli to get auth token.

**Comment by tiredofit** [comment]
All good things must come to an end it sounds like - I'll do some research on this next week - this is the first I am hearing about this.. If you clone this git repo you can change ENV variable to the version you need and build it on your end - however also you can try out tiredofit/gcds:5.1.7 which should also give you what you need.

**Comment by xueshanf** [comment]
Hello @tiredofit You can close this issue. The syntax error is fixed, but I have other issues to test your docker  with my M1 laptop. I was able to get refresh oauth token from a GUI desktop app and updated all the secrets, new xml conf file and I can move on. Thanks!

**Comment by tiredofit** [comment]
`6.0.0` has been rewritten and integrates the GUI inside the image as I have started to experience authentication issues as well. I hope can help for you going forward!
